dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.2
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    optimizer:
      enabled: True
      runs: 1000000
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.5.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'
      - '@openzeppelinUpgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.0'
dotenv: .env
networks:
  default: development
  development:
    base_fee: 250000000000000000 # it's the premium. it costs 0.25 LINK per request.
    gas_price_link: 1000000000 # calculated value based on the gas price of the chain | LINK pre gas
    vrf_sub_fund_amount: 10000000000000000000 # 10 LINK
    key_hash: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
    call_back_gas_limit: 500000
  sepolia:
    coordinator: "0x8103B0A8A00be2DDC778e6e7eaa21791Cd364625"
    subscription_id: 496
    key_hash: "0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c"
    call_back_gas_limit: 100000
  goerli:
    coordinator: "0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D"
    subscription_id: 44
    key_hash: "0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15"
    call_back_gas_limit: 100000
  mumbai:
    coordinator: "0x7a1BaC17Ccc5b313516C5E16fb24f7659aA5ebed"
    subscription_id: 3665
    key_hash: "0x4b09e658ed251bcafeebbc69400383d49f344ace09b9576fe248bb02c003fe9f"
    call_back_gas_limit: 100000
  bsc-test:
    coordinator: "0x6A2AAd07396B36Fe02a22b33cf443582f682c82f"
    subscription_id: 2756
    key_hash: "0xd4bb89654db74673a187bd804519e65e3f71a52bc55f11da7601a13dcf505314"
    call_back_gas_limit: 100000
wallets:
  from_key: ${PRIVATE_KEY}
